# Metasyn Tutorial: Time-Series Dependencies and Logical Constraints

In this tutorial, we explore how to model time-series data with start and end dates, and how to add column dependency relationships and constraints to synthetic data using the implemented dunder methods.

### 0. Install and import

First, let's install metasyn if you haven't done so already.

In [1]:
# %pip install metasyn

Now let's import the packages we need.

In [2]:
import polars as pl

from metasyn import demo_data
from metasyn.builder import MetaFrameBuilder
from metasyn.distribution import DiscreteTruncatedNormalDistribution
from metasyn.distribution.base import (
    ColumnReference,
    IfThenElse,
)

### 1. Synthesising time-series data

A common challenge with time-series datasets is that columns can be related to each other. For example, in a hospital admissions dataset the `discharge_date` should always come *after* the `admission_date`. By default, metasyn treats each column independently, so this constraint is not preserved.

Let's load our hospital admissions dataset to see this in action.

In [3]:
df = demo_data("hospital_admissions")

df.head()

shape: (5, 8)
┌────────────┬────────────────┬────────────────┬───────────────┬─────┬───────────┬───────────┬─────┐
│ Patient_id ┆ Admission_date ┆ Discharge_date ┆ Length_of_sta ┆ Age ┆ Height_cm ┆ Weight_kg ┆ Sex │
│ ---        ┆ ---            ┆ ---            ┆ y_days        ┆ --- ┆ ---       ┆ ---       ┆ --- │
│ i64        ┆ datetime[μs]   ┆ datetime[μs]   ┆ ---           ┆ i64 ┆ i64       ┆ i64       ┆ str │
│            ┆                ┆                ┆ i64           ┆     ┆           ┆           ┆     │
╞════════════╪════════════════╪════════════════╪═══════════════╪═════╪═══════════╪═══════════╪═════╡
│ 1          ┆ 2023-01-04     ┆ 2023-01-06     ┆ 2             ┆ 44  ┆ 164       ┆ 67        ┆ F   │
│            ┆ 00:00:00       ┆ 00:00:00       ┆               ┆     ┆           ┆           ┆     │
│ 2          ┆ 2023-01-08     ┆ 2023-01-18     ┆ 10            ┆ 78  ┆ 154       ┆ 57        ┆ F   │
│            ┆ 00:00:00       ┆ 00:00:00       ┆               ┆     ┆           ┆           ┆     │
│ 3          ┆ 2023-01-08     ┆ 2023-01-19     ┆ 11            ┆ 18  ┆ 167       ┆ 77        ┆ M   │
│            ┆ 00:00:00       ┆ 00:00:00       ┆               ┆     ┆           ┆           ┆     │
│ 4          ┆ 2023-01-08     ┆ 2023-01-24     ┆ 16            ┆ 83  ┆ 177       ┆ 95        ┆ F   │
│            ┆ 00:00:00       ┆ 00:00:00       ┆               ┆     ┆           ┆           ┆     │
│ 5          ┆ 2023-01-15     ┆ 2023-01-21     ┆ 6             ┆ 9   ┆ 138       ┆ 25        ┆ M   │
│            ┆ 00:00:00       ┆ 00:00:00       ┆               ┆     ┆           ┆           ┆     │
└────────────┴────────────────┴────────────────┴───────────────┴─────┴───────────┴───────────┴─────┘

If we fit and synthesise without any additional instructions, the dates are generated independently. Let's check how often this produces inconsistent results.

In [4]:
builder = MetaFrameBuilder()
builder.add_dataframe(df, None)

synth = builder.fit().synthesize()

n_inconsistent = (synth["Discharge_date"] < synth["Admission_date"]).sum()
print(f"\nRows where Discharge_date < Admission_date: {n_inconsistent} / {len(synth)}")

synth.head()

100%|██████████| 8/8 [00:00<00:00,  8.39it/s]
  Patient_id: 100%|██████████| 8/8 [00:00<00:00, 469.79variables/s]

Rows where Discharge_date < Admission_date: 55 / 100

shape: (5, 8)
┌────────────┬────────────────┬────────────────┬───────────────┬─────┬───────────┬───────────┬─────┐
│ Patient_id ┆ Admission_date ┆ Discharge_date ┆ Length_of_sta ┆ Age ┆ Height_cm ┆ Weight_kg ┆ Sex │
│ ---        ┆ ---            ┆ ---            ┆ y_days        ┆ --- ┆ ---       ┆ ---       ┆ --- │
│ i64        ┆ datetime[μs]   ┆ datetime[μs]   ┆ ---           ┆ i64 ┆ i64       ┆ i64       ┆ str │
│            ┆                ┆                ┆ i64           ┆     ┆           ┆           ┆     │
╞════════════╪════════════════╪════════════════╪═══════════════╪═════╪═══════════╪═══════════╪═════╡
│ 1          ┆ 2023-05-24     ┆ 2023-04-25     ┆ 10            ┆ 70  ┆ 189       ┆ 79        ┆ F   │
│            ┆ 00:00:00       ┆ 00:00:00       ┆               ┆     ┆           ┆           ┆     │
│ 2          ┆ 2024-03-06     ┆ 2024-02-08     ┆ 11            ┆ 43  ┆ 195       ┆ 60        ┆ F   │
│            ┆ 00:00:00       ┆ 00:00:00       ┆               ┆     ┆           ┆           ┆     │
│ 3          ┆ 2024-01-18     ┆ 2023-07-07     ┆ 10            ┆ 27  ┆ 154       ┆ 91        ┆ F   │
│            ┆ 00:00:00       ┆ 00:00:00       ┆               ┆     ┆           ┆           ┆     │
│ 4          ┆ 2024-08-28     ┆ 2023-07-18     ┆ 4             ┆ 84  ┆ 158       ┆ 104       ┆ F   │
│            ┆ 00:00:00       ┆ 00:00:00       ┆               ┆     ┆           ┆           ┆     │
│ 5          ┆ 2024-11-08     ┆ 2024-08-23     ┆ 16            ┆ 25  ┆ 188       ┆ 88        ┆ M   │
│            ┆ 00:00:00       ┆ 00:00:00       ┆               ┆     ┆           ┆           ┆     │
└────────────┴────────────────┴────────────────┴───────────────┴─────┴───────────┴───────────┴─────┘

As we can see, there are some inconsistent rows. To fix this, we can add a hidden `duration_days` column that holds the difference in days between `Discharge_date` and `Admission_date`. Metasyn fits a distribution to the new column, which can then be used to compute `Discharge_date = Admission_date + duration_days`. Setting `hidden=True` ensures the helper column does **not** appear in the final output.

Note that `ColumnReference` refers to the values in a column at synthesis time, and can be used to build expressions between columns.

In [5]:
builder = MetaFrameBuilder()
builder.add_dataframe(df, None)

# Add a column and mark as hidden
builder.add_column("duration_days", hidden=True)

# Create a series for the difference between discharge_date and admission_date, and use it to derive discharge_date
builder["duration_days"].series = ColumnReference("Discharge_date") - ColumnReference("Admission_date")
builder["Discharge_date"].distribution = ColumnReference("Admission_date") + ColumnReference("duration_days")

synth = builder.fit().synthesize()

n_inconsistent = (synth["Discharge_date"] < synth["Admission_date"]).sum()
print(f"\nRows where Discharge_date < Admission_date: {n_inconsistent} / {len(synth)}")

synth

100%|██████████| 9/9 [00:00<00:00, 10.26it/s]
  Patient_id: 100%|██████████| 9/9 [00:00<00:00, 521.56variables/s]

Rows where Discharge_date < Admission_date: 0 / 100

shape: (100, 8)
┌────────────┬────────────────┬────────────────┬───────────────┬─────┬───────────┬───────────┬─────┐
│ Patient_id ┆ Admission_date ┆ Discharge_date ┆ Length_of_sta ┆ Age ┆ Height_cm ┆ Weight_kg ┆ Sex │
│ ---        ┆ ---            ┆ ---            ┆ y_days        ┆ --- ┆ ---       ┆ ---       ┆ --- │
│ i64        ┆ datetime[μs]   ┆ datetime[μs]   ┆ ---           ┆ i64 ┆ i64       ┆ i64       ┆ str │
│            ┆                ┆                ┆ i64           ┆     ┆           ┆           ┆     │
╞════════════╪════════════════╪════════════════╪═══════════════╪═════╪═══════════╪═══════════╪═════╡
│ 1          ┆ 2024-06-09     ┆ 2024-06-29     ┆ 16            ┆ 30  ┆ 185       ┆ 12        ┆ M   │
│            ┆ 00:00:00       ┆ 00:00:00       ┆               ┆     ┆           ┆           ┆     │
│ 2          ┆ 2024-01-31     ┆ 2024-02-09     ┆ 14            ┆ 20  ┆ 124       ┆ 74        ┆ M   │
│            ┆ 00:00:00       ┆ 00:00:00       ┆               ┆     ┆           ┆           ┆     │
│ 3          ┆ 2023-02-15     ┆ 2023-02-25     ┆ 11            ┆ 6   ┆ 157       ┆ 119       ┆ F   │
│            ┆ 00:00:00       ┆ 00:00:00       ┆               ┆     ┆           ┆           ┆     │
│ 4          ┆ 2023-03-05     ┆ 2023-03-23     ┆ 16            ┆ 56  ┆ 170       ┆ 82        ┆ F   │
│            ┆ 00:00:00       ┆ 00:00:00       ┆               ┆     ┆           ┆           ┆     │
│ 5          ┆ 2023-08-12     ┆ 2023-08-21     ┆ 15            ┆ 80  ┆ 139       ┆ 75        ┆ M   │
│            ┆ 00:00:00       ┆ 00:00:00       ┆               ┆     ┆           ┆           ┆     │
│ …          ┆ …              ┆ …              ┆ …             ┆ …   ┆ …         ┆ …         ┆ …   │
│ 96         ┆ 2024-11-06     ┆ 2024-11-17     ┆ 10            ┆ 76  ┆ 145       ┆ 56        ┆ F   │
│            ┆ 00:00:00       ┆ 00:00:00       ┆               ┆     ┆           ┆           ┆     │
│ 97         ┆ 2024-08-09     ┆ 2024-08-15     ┆ 9             ┆ 50  ┆ 154       ┆ 52        ┆ M   │
│            ┆ 00:00:00       ┆ 00:00:00       ┆               ┆     ┆           ┆           ┆     │
│ 98         ┆ 2023-12-24     ┆ 2024-01-13     ┆ 9             ┆ 89  ┆ 157       ┆ 84        ┆ M   │
│            ┆ 00:00:00       ┆ 00:00:00       ┆               ┆     ┆           ┆           ┆     │
│ 99         ┆ 2024-11-23     ┆ 2024-12-08     ┆ 17            ┆ 83  ┆ 177       ┆ 59        ┆ M   │
│            ┆ 00:00:00       ┆ 00:00:00       ┆               ┆     ┆           ┆           ┆     │
│ 100        ┆ 2024-05-19     ┆ 2024-05-29     ┆ 13            ┆ 34  ┆ 167       ┆ 88        ┆ F   │
│            ┆ 00:00:00       ┆ 00:00:00       ┆               ┆     ┆           ┆           ┆     │
└────────────┴────────────────┴────────────────┴───────────────┴─────┴───────────┴───────────┴─────┘

No more inconsistent rows.

This dataframe already contains a duration column, `Length_of_stay_days`, so we do not need to create a hidden helper column for this example. Instead, we convert `Length_of_stay_days` from an integer column to a Polars duration column, so metasyn recognizes it as a duration.

In [6]:
# Check the Polars documentation for the right way to convert your column to a duration.
df_duration = df.with_columns(
    pl.duration(days=pl.col("Length_of_stay_days")).alias("Length_of_stay_days")
)

df_duration.head()

shape: (5, 8)
┌────────────┬────────────────┬────────────────┬───────────────┬─────┬───────────┬───────────┬─────┐
│ Patient_id ┆ Admission_date ┆ Discharge_date ┆ Length_of_sta ┆ Age ┆ Height_cm ┆ Weight_kg ┆ Sex │
│ ---        ┆ ---            ┆ ---            ┆ y_days        ┆ --- ┆ ---       ┆ ---       ┆ --- │
│ i64        ┆ datetime[μs]   ┆ datetime[μs]   ┆ ---           ┆ i64 ┆ i64       ┆ i64       ┆ str │
│            ┆                ┆                ┆ duration[μs]  ┆     ┆           ┆           ┆     │
╞════════════╪════════════════╪════════════════╪═══════════════╪═════╪═══════════╪═══════════╪═════╡
│ 1          ┆ 2023-01-04     ┆ 2023-01-06     ┆ 2d            ┆ 44  ┆ 164       ┆ 67        ┆ F   │
│            ┆ 00:00:00       ┆ 00:00:00       ┆               ┆     ┆           ┆           ┆     │
│ 2          ┆ 2023-01-08     ┆ 2023-01-18     ┆ 10d           ┆ 78  ┆ 154       ┆ 57        ┆ F   │
│            ┆ 00:00:00       ┆ 00:00:00       ┆               ┆     ┆           ┆           ┆     │
│ 3          ┆ 2023-01-08     ┆ 2023-01-19     ┆ 11d           ┆ 18  ┆ 167       ┆ 77        ┆ M   │
│            ┆ 00:00:00       ┆ 00:00:00       ┆               ┆     ┆           ┆           ┆     │
│ 4          ┆ 2023-01-08     ┆ 2023-01-24     ┆ 16d           ┆ 83  ┆ 177       ┆ 95        ┆ F   │
│            ┆ 00:00:00       ┆ 00:00:00       ┆               ┆     ┆           ┆           ┆     │
│ 5          ┆ 2023-01-15     ┆ 2023-01-21     ┆ 6d            ┆ 9   ┆ 138       ┆ 25        ┆ M   │
│            ┆ 00:00:00       ┆ 00:00:00       ┆               ┆     ┆           ┆           ┆     │
└────────────┴────────────────┴────────────────┴───────────────┴─────┴───────────┴───────────┴─────┘

Because metasyn supports duration columns, we can define `Discharge_date` as the sum of `Admission_date` and `Length_of_stay_days`.

In [7]:
builder = MetaFrameBuilder()
builder.add_dataframe(df_duration, None)

builder["Discharge_date"].distribution = ColumnReference("Admission_date") + ColumnReference("Length_of_stay_days")

builder.fit().synthesize()

100%|██████████| 8/8 [00:00<00:00, 10.08it/s]
  Patient_id: 100%|██████████| 8/8 [00:00<00:00, 519.76variables/s]

shape: (100, 8)
┌────────────┬────────────────┬────────────────┬───────────────┬─────┬───────────┬───────────┬─────┐
│ Patient_id ┆ Admission_date ┆ Discharge_date ┆ Length_of_sta ┆ Age ┆ Height_cm ┆ Weight_kg ┆ Sex │
│ ---        ┆ ---            ┆ ---            ┆ y_days        ┆ --- ┆ ---       ┆ ---       ┆ --- │
│ i64        ┆ datetime[μs]   ┆ datetime[μs]   ┆ ---           ┆ i64 ┆ i64       ┆ i64       ┆ str │
│            ┆                ┆                ┆ duration[μs]  ┆     ┆           ┆           ┆     │
╞════════════╪════════════════╪════════════════╪═══════════════╪═════╪═══════════╪═══════════╪═════╡
│ 1          ┆ 2023-10-12     ┆ 2023-10-28     ┆ 16d           ┆ 45  ┆ 147       ┆ 76        ┆ F   │
│            ┆ 00:00:00       ┆ 00:00:00       ┆               ┆     ┆           ┆           ┆     │
│ 2          ┆ 2024-02-15     ┆ 2024-02-26     ┆ 11d           ┆ 44  ┆ 155       ┆ 81        ┆ F   │
│            ┆ 00:00:00       ┆ 00:00:00       ┆               ┆     ┆           ┆           ┆     │
│ 3          ┆ 2024-07-09     ┆ 2024-07-12     ┆ 3d            ┆ 61  ┆ 200       ┆ 47        ┆ F   │
│            ┆ 00:00:00       ┆ 00:00:00       ┆               ┆     ┆           ┆           ┆     │
│ 4          ┆ 2023-09-01     ┆ 2023-09-11     ┆ 10d           ┆ 77  ┆ 155       ┆ 66        ┆ M   │
│            ┆ 00:00:00       ┆ 00:00:00       ┆               ┆     ┆           ┆           ┆     │
│ 5          ┆ 2024-04-20     ┆ 2024-04-22     ┆ 2d            ┆ 51  ┆ 159       ┆ 66        ┆ M   │
│            ┆ 00:00:00       ┆ 00:00:00       ┆               ┆     ┆           ┆           ┆     │
│ …          ┆ …              ┆ …              ┆ …             ┆ …   ┆ …         ┆ …         ┆ …   │
│ 96         ┆ 2023-05-24     ┆ 2023-06-11     ┆ 18d           ┆ 61  ┆ 178       ┆ 31        ┆ M   │
│            ┆ 00:00:00       ┆ 00:00:00       ┆               ┆     ┆           ┆           ┆     │
│ 97         ┆ 2024-03-30     ┆ 2024-04-05     ┆ 6d            ┆ 53  ┆ 180       ┆ 77        ┆ M   │
│            ┆ 00:00:00       ┆ 00:00:00       ┆               ┆     ┆           ┆           ┆     │
│ 98         ┆ 2023-07-02     ┆ 2023-07-12     ┆ 10d           ┆ 25  ┆ 162       ┆ 50        ┆ F   │
│            ┆ 00:00:00       ┆ 00:00:00       ┆               ┆     ┆           ┆           ┆     │
│ 99         ┆ 2024-06-21     ┆ 2024-07-06     ┆ 15d           ┆ 66  ┆ 163       ┆ 71        ┆ M   │
│            ┆ 00:00:00       ┆ 00:00:00       ┆               ┆     ┆           ┆           ┆     │
│ 100        ┆ 2023-05-28     ┆ 2023-05-30     ┆ 2d            ┆ 45  ┆ 175       ┆ 57        ┆ F   │
│            ┆ 00:00:00       ┆ 00:00:00       ┆               ┆     ┆           ┆           ┆     │
└────────────┴────────────────┴────────────────┴───────────────┴─────┴───────────┴───────────┴─────┘

The synthesized `Discharge_date` values now align with the corresponding `Admission_date` and `Length_of_stay_days` values.

### 2. Logical expressions and conditions

If a boolean column is fully determined by another column, you can encode that dependency directly. For example, if the dataset contains an `Adult` column, you can define it as `builder["Adult"].distribution = ColumnReference("Age") > 18`. This keeps synthesized data internally consistent without post-processing.

The comparison and logical operators let you derive boolean columns from expressions. The table below lists the implemented operators and example usage. For readability, the examples show column names directly, but in practice, reference a column with `ColumnReference()`, for example `ColumnReference("Age")`.

| Dunder | Operator | Example |
|---|---|---|
| `__add__` | `a + b` | `Age + 10` |
| `__sub__` | `a - b` | `Age - 10` |
| `__mul__` | `a * b` | `Weight_kg * 2` |
| `__truediv__` | `a / b` | `Weight_kg / 2` |
| `__pow__` | `a ** b` | `Weight_kg ** 2` |
| `__neg__` | `-a` | `-Weight_kg` |
| `__invert__` | `not a` | `not Adult` |
| `__and__` | `a & b` | `Adult & (Sex == "male")` |
| `__or__` | `a \| b` | `Adult \| Child` |
| `__eq__` | `a == b` | `Sex == "female"` |
| `__ne__` | `a != b` | `Sex != "male"` |
| `__lt__` | `a < b` | `Age < 18` |
| `__gt__` | `a > b` | `Age > 17` |
| `__le__` | `a <= b` | `Age <= 17` |
| `__ge__` | `a >= b` | `Age >= 18` |

In [8]:
# Example without relations or constraints

# Create example data with boolean "Adult" column
df = df.with_columns(
    (pl.col("Age") > 18).alias("Adult"),
)

builder = MetaFrameBuilder()
builder.add_dataframe(df, None)

synth = builder.fit().synthesize()

n_mismatches = synth.filter(
    (pl.col("Age") > 18) & ~pl.col("Adult")
).height

print(f"\nRows where age > 18 but Adult is false: {n_mismatches} / {len(synth)}")

synth[["Age", "Adult"]]

100%|██████████| 9/9 [00:00<00:00, 10.81it/s]
  Patient_id: 100%|██████████| 9/9 [00:00<00:00, 581.75variables/s]

Rows where age > 18 but Adult is false: 21 / 100

shape: (100, 2)
┌─────┬───────┐
│ Age ┆ Adult │
│ --- ┆ ---   │
│ i64 ┆ bool  │
╞═════╪═══════╡
│ 89  ┆ true  │
│ 33  ┆ false │
│ 44  ┆ true  │
│ 9   ┆ false │
│ 65  ┆ false │
│ …   ┆ …     │
│ 2   ┆ false │
│ 6   ┆ true  │
│ 25  ┆ true  │
│ 71  ┆ false │
│ 6   ┆ true  │
└─────┴───────┘

Let's fix the inconsistency.

In [9]:
# Add relations or constraints
builder["Adult"].distribution = ColumnReference("Age") > 18

synth = builder.fit().synthesize()

n_mismatches = synth.filter(
    (pl.col("Age") > 18) & ~pl.col("Adult")
).height

print(f"\nRows where age > 18 but Adult is false: {n_mismatches} / {len(synth)}")

synth[["Age", "Adult"]]

100%|██████████| 9/9 [00:00<00:00, 11.57it/s]
  Patient_id: 100%|██████████| 9/9 [00:00<00:00, 651.62variables/s]

Rows where age > 18 but Adult is false: 0 / 100

shape: (100, 2)
┌─────┬───────┐
│ Age ┆ Adult │
│ --- ┆ ---   │
│ i64 ┆ bool  │
╞═════╪═══════╡
│ 79  ┆ true  │
│ 80  ┆ true  │
│ 14  ┆ false │
│ 48  ┆ true  │
│ 72  ┆ true  │
│ …   ┆ …     │
│ 37  ┆ true  │
│ 39  ┆ true  │
│ 52  ┆ true  │
│ 57  ┆ true  │
│ 66  ┆ true  │
└─────┴───────┘

#### IfThenElse example

Sometimes the distribution of a column depends on the value of another column. For example, `Height_cm` tends to differ between male and female patients. With `IfThenElse`, you can specify a different distribution or value for each group.

In [10]:
# Males: TruncatedNormal centred at 180 cm; females: centred at 170 cm
builder["Height_cm"].distribution = IfThenElse(
    ColumnReference("Sex") == "M",
    DiscreteTruncatedNormalDistribution(lower=160, upper=200, mean=180, sd=10),
    DiscreteTruncatedNormalDistribution(lower=150, upper=190, mean=170, sd=10),
)

synth = builder.fit().synthesize()
synth[["Sex", "Height_cm"]].head(10)

100%|██████████| 9/9 [00:00<00:00, 14.09it/s]
  Patient_id: 100%|██████████| 9/9 [00:00<00:00, 705.40variables/s]

shape: (10, 2)
┌─────┬───────────┐
│ Sex ┆ Height_cm │
│ --- ┆ ---       │
│ str ┆ i64       │
╞═════╪═══════════╡
│ F   ┆ 154       │
│ F   ┆ 164       │
│ M   ┆ 179       │
│ M   ┆ 194       │
│ F   ┆ 170       │
│ M   ┆ 189       │
│ F   ┆ 178       │
│ F   ┆ 160       │
│ F   ┆ 170       │
│ M   ┆ 176       │
└─────┴───────────┘

Actually, this dataset includes more complex dependencies: `Height_cm` and `Weight_kg` are strongly associated with age.
For example, a 6-year-old is very unlikely to be 200 cm tall or weigh 100 kg.

To make synthetic data more realistic, we can divide age into categories and assign plausible ranges to each group:

- **0-2 years:** height 50-90 cm, weight 3-14 kg
- **3-12 years:** height 95-155 cm, weight 14-50 kg
- **13-17 years:** height 145-190 cm, weight 40-90 kg
- **18+ years:** height 145-210 cm, weight 45-150 kg

These ranges are useful defaults for synthetic data generation, but edge-case combinations can still appear.

In the example below, we combine logical and conditional operators to define distributions across `Age` ranges.

In [11]:
builder = MetaFrameBuilder()
builder.add_dataframe(df, None)

builder["Weight_kg"].distribution = IfThenElse(
    ColumnReference("Age") <= 2,
    DiscreteTruncatedNormalDistribution(lower=3, upper=14, mean=8, sd=2),
    IfThenElse(
        ColumnReference("Age") <= 12,
        DiscreteTruncatedNormalDistribution(lower=14, upper=50, mean=30, sd=10),
        IfThenElse(
            ColumnReference("Age") <= 17,
            DiscreteTruncatedNormalDistribution(lower=40, upper=90, mean=65, sd=10),
            DiscreteTruncatedNormalDistribution(lower=50, upper=120, mean=75, sd=15),
        ),
    ),
)

builder["Height_cm"].distribution = IfThenElse(
    ColumnReference("Age") <= 2,
    DiscreteTruncatedNormalDistribution(lower=50, upper=90, mean=70, sd=10),
    IfThenElse(
        ColumnReference("Age") <= 12,
        DiscreteTruncatedNormalDistribution(lower=95, upper=155, mean=125, sd=15),
        IfThenElse(
            ColumnReference("Age") <= 17,
            DiscreteTruncatedNormalDistribution(lower=145, upper=190, mean=167, sd=12),
            DiscreteTruncatedNormalDistribution(lower=145, upper=210, mean=172, sd=12),
        ),
    ),
)

synth = builder.fit().synthesize()

synth

100%|██████████| 9/9 [00:00<00:00, 14.74it/s]
  Patient_id: 100%|██████████| 9/9 [00:00<00:00, 597.82variables/s]

shape: (100, 9)
┌────────────┬──────────────┬──────────────┬─────────────┬───┬───────────┬───────────┬─────┬───────┐
│ Patient_id ┆ Admission_da ┆ Discharge_da ┆ Length_of_s ┆ … ┆ Height_cm ┆ Weight_kg ┆ Sex ┆ Adult │
│ ---        ┆ te           ┆ te           ┆ tay_days    ┆   ┆ ---       ┆ ---       ┆ --- ┆ ---   │
│ i64        ┆ ---          ┆ ---          ┆ ---         ┆   ┆ i64       ┆ i64       ┆ str ┆ bool  │
│            ┆ datetime[μs] ┆ datetime[μs] ┆ i64         ┆   ┆           ┆           ┆     ┆       │
╞════════════╪══════════════╪══════════════╪═════════════╪═══╪═══════════╪═══════════╪═════╪═══════╡
│ 1          ┆ 2024-02-19   ┆ 2023-02-08   ┆ 13          ┆ … ┆ 169       ┆ 69        ┆ F   ┆ true  │
│            ┆ 00:00:00     ┆ 00:00:00     ┆             ┆   ┆           ┆           ┆     ┆       │
│ 2          ┆ 2024-02-08   ┆ 2024-03-22   ┆ 12          ┆ … ┆ 167       ┆ 64        ┆ F   ┆ true  │
│            ┆ 00:00:00     ┆ 00:00:00     ┆             ┆   ┆           ┆           ┆     ┆       │
│ 3          ┆ 2023-11-17   ┆ 2024-11-12   ┆ 12          ┆ … ┆ 167       ┆ 71        ┆ M   ┆ true  │
│            ┆ 00:00:00     ┆ 00:00:00     ┆             ┆   ┆           ┆           ┆     ┆       │
│ 4          ┆ 2023-02-06   ┆ 2024-08-21   ┆ 4           ┆ … ┆ 171       ┆ 80        ┆ M   ┆ false │
│            ┆ 00:00:00     ┆ 00:00:00     ┆             ┆   ┆           ┆           ┆     ┆       │
│ 5          ┆ 2023-11-12   ┆ 2023-05-07   ┆ 12          ┆ … ┆ 166       ┆ 51        ┆ F   ┆ false │
│            ┆ 00:00:00     ┆ 00:00:00     ┆             ┆   ┆           ┆           ┆     ┆       │
│ …          ┆ …            ┆ …            ┆ …           ┆ … ┆ …         ┆ …         ┆ …   ┆ …     │
│ 96         ┆ 2023-02-11   ┆ 2024-02-22   ┆ 18          ┆ … ┆ 128       ┆ 25        ┆ M   ┆ true  │
│            ┆ 00:00:00     ┆ 00:00:00     ┆             ┆   ┆           ┆           ┆     ┆       │
│ 97         ┆ 2023-03-30   ┆ 2024-08-23   ┆ 1           ┆ … ┆ 159       ┆ 77        ┆ F   ┆ true  │
│            ┆ 00:00:00     ┆ 00:00:00     ┆             ┆   ┆           ┆           ┆     ┆       │
│ 98         ┆ 2024-06-20   ┆ 2023-07-11   ┆ 13          ┆ … ┆ 177       ┆ 60        ┆ M   ┆ true  │
│            ┆ 00:00:00     ┆ 00:00:00     ┆             ┆   ┆           ┆           ┆     ┆       │
│ 99         ┆ 2024-04-16   ┆ 2023-08-25   ┆ 19          ┆ … ┆ 181       ┆ 108       ┆ M   ┆ true  │
│            ┆ 00:00:00     ┆ 00:00:00     ┆             ┆   ┆           ┆           ┆     ┆       │
│ 100        ┆ 2024-10-16   ┆ 2024-12-11   ┆ 12          ┆ … ┆ 207       ┆ 81        ┆ F   ┆ true  │
│            ┆ 00:00:00     ┆ 00:00:00     ┆             ┆   ┆           ┆           ┆     ┆       │
└────────────┴──────────────┴──────────────┴─────────────┴───┴───────────┴───────────┴─────┴───────┘

As you can see, height and weight are adjusted to match the different age groups in the synthesized data.

### 3. Important note

When defining relationships between columns, it is usually safer to **preserve the broad structure of the data** than to reproduce every numerical detail exactly. Metasyn can help reduce disclosure risk through its modelling choices and constraints, but it cannot prevent users from encoding **sensitive information indirectly through overly specific rules**. Aim for relationships that are realistic enough for the intended use case, while still remaining approximate.